### ISSUE TITLE
Validate Events in Rule Signature vs Events in Function Parameters

### ISSUE THREAD

**Issue by rheum** [compiler-dept/event-compiler#20]
Example of what validation should detect:

    event SampleEvent { pos, time };
    event InheritanceEvent extends SampleEvent { angle };
    event OtherEvent { foo };

    SampleEvent example(SampleEvent sampleEventA, SampleEvent sampleEventB) :=
    {
        pos = 3 * sampleEventA.pos,
        time = [12.3],
    };

    PosEqual: [InheritanceEvent, SampleEvent : sample_predicate] -> example; // Should be allowed!
    PosEqual: [OtherEvent, SampleEvent : sample_predicate] -> example; // Should not be allowed!

**Comment by apfohl** [comment]
In my opinion, these are the only valid once:

    PosEqual: [SampleEvent, SampleEvent : sample_predicate] -> example;
    PosSample: [SampleEvent, SampleEvent] -> example;
    Static: [] -> static;

Do you agree? I will change the grammar accordingly.

**Comment by apfohl** [comment]
@steup: What do you think?

**Comment by steup** [comment]
Actually I think that this limitation is too strong. A rule is quite possible,  that creates a new Event Type based on different ones. An example is:
event SpeedEvent extends Basic Event { speed };
event DetectionEvent extends BasicEvent { id };
InferSpeed: [DetectionEvent, Detection Event, SpeedEvent : idEqual, timeUnEqual] -> doIt;

Hopefully I understood your rule syntax correctly.

**Comment by apfohl** [comment]
So, your ```doIt``` function takes three events as input. Also the two predicates take these three inputs. What type of event is generated by ```doIt``` is only defined by the declaration of the function ```doIt```.

    event SpeedEvent extends Basic Event { speed };
    event DetectionEvent extends BasicEvent { id };

    event ReturnEvent { time };
    ReturnEvent doIt(DetectionEvent de1, DetectionEvent de2, SpeedEvent se) := { ... };

    InferSpeed: [DetectionEvent, DetectionEvent, SpeedEvent : idEqual, timeUnEqual] -> doIt;
