### ISSUE TITLE
Operators for vectors

### ISSUE THREAD

**Issue by apfohl** [compiler-dept/event-compiler#29]
@steup: I've implemented some of the operators to build predicates. I'm not shure how to implement the rest. Missing operators are:

- vector < vector
- vector > vector

How do I determine if a vector is smaller than another one.

**Comment by steup** [comment]
The operations need to be executed element-wise in the vector and result in a vector of bools
Afterwards a norm may be applied to the vector like min or max (and or or) resulting in  scalar bool
