### ISSUE TITLE
segmentation fault in rule declaration

### ISSUE THREAD

**Issue by apfohl** [compiler-dept/event-compiler#33]
The following produces a segfault while cleaning up memory because of wrong parser input.

    Rule: [SampleEvent, pred] -> constfun;

**Comment by rheum** [comment]
? I believe this isn't valid .ev syntax?

**Comment by apfohl** [comment]
Right, it isn't. But if you try to compile it, the compiler will crash with a segfault.

**Comment by rheum** [comment]
Ah, ok. I will take a look at it sometime this week.
