### ISSUE TITLE
M48 M95 Header

### ISSUE THREAD

**Issue by maknoll** [compiler-dept/event-compiler#38]
lexer:

    "%"                         return PERCENT;
    "M48"                       return HEADERSTART;
    "M95"                       return HEADEREND;

parser:

    header ::= HEADERSTART statement_list HEADEREND.
    header ::= HEADERSTART statement_list PERCENT.
    header ::= PERCENT statement_list HEADEREND.
    header ::= PERCENT statement_list PERCENT. {
        fprintf(stderr, "%s", "Header\n");
    }

mimimi:

    g-compiler master modified % ./g-compiler
    Syntax Error!
    Assertion failed: (yyruleno<sizeof(yyRuleInfo)/sizeof(yyRuleInfo[0])), function yy_reduce, file  parser.c, line 924.
    [1]    38907 abort      ./g-compiler

Weißt du warum, @apfohl?

**Comment by apfohl** [comment]
This is totally the wrong repository. Please ask again in your repository.

**Comment by maknoll** [comment]
Ooooops
